version: "3.9"

services:
  fastapi:
    build:
      context: .
    image: fastapi_echo:latest
    ports:
      - target: 80
        published: 8000
      - target: 5678
        published: 5678
      - target: 4444
        published: 4444        
    volumes:
      - type: bind
        source: ./app
        target: /app
    command: uvicorn main:app --reload --host 0.0.0.0 --port 80
